### ISSUE TITLE
Publish 1.2.0?

### ISSUE THREAD

**Issue by skozin** [grempe/secrets.js#5]
Currently, the latest release published to NPM is `1.1.0`, which doesn't include `secrets.seedRNG()` API from the master branch (which is marked `1.2.0` in `package.json`).

Is there any reason `1.2.0` is not published? Maybe it's worth publishing it?

**Comment by thEpisode** [comment]
Maybe this repo is not maintained

**Comment by grempe** [comment]
I'll be publishing a new version with some minor cleanups and modernization shortly.

**Comment by grempe** [comment]
Version 2.0.0 with some minor cleanups and modernization has been pushed.

https://www.npmjs.com/package/secrets.js-grempe

**Comment by thEpisode** [comment]
minor changes not require a change of version, but it's great idea

**Comment by grempe** [comment]
@thEpisode Version 2.0 had a breaking change necessitating a `major` version bump according to SemVer.

https://github.com/grempe/secrets.js#changelog
