### ISSUE TITLE
How to check if the combined secret is the original secret or not ?

### ISSUE THREAD

**Issue by prahaladbelavadi** [grempe/secrets.js#6]
If XYZ is a secret shared in to 10 shares with a threshold of 5, how can I verify that the combination of any random 6 shares is YXY and not XYZ if I'm unaware of it ?

**Comment by prahaladbelavadi** [comment]
In the example,
``
// combine 5 shares
comb = secrets.combine( shares.slice(4,9) );
console.log(comb === key); // => true
``
How do I verify comb is key if I don't know the key ?

**Comment by gorgos** [comment]
You can't. See [possible future enhancements](https://github.com/grempe/secrets.js#possible-future-enhancements).

> Add a checksum to the share format to validate its integrity and reject combine() of bad shares. (Requires share format change)

**Comment by prahaladbelavadi** [comment]
I hadn't seen that
Thanks! @gorgos :)

**Comment by amper5and** [comment]
@gorgos Those "possible future enhancements" were the TODOs on my original project :). I doubt grempe had them in mind too. They just came with the repo :).
