### ISSUE TITLE
`radix` doesn't appear used, as bin2hex is hard-coded to 16

### ISSUE THREAD

**Issue by mortoray** [grempe/secrets.js#95]
I'm unclear on what the `radix` is used for, since `bin2hex` is hard-coded to use 16 as the radix. How can I get output that is base 36 encoded?

I tried playing around with various parts of the code, changing 16 -> radix, but not having much luck.

**Comment by mortoray** [comment]
Somehow the radix isn't surviving to the splitNumStringToIntArray function. I'll assume it's a fault elsewhere in my code.

**Comment by grempe** [comment]
I don't think radix is exposed anywhere as a configurable value so it should be thought of as a constant. Other output/input formats, other than what is documented, are not supported at this time.

Cheers.
